# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\"_\n\x0bTransaction\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x05 \x01(\r\"M\n\x11SignedTransaction\x12%\n\x0btransaction\x18\x01 \x01(\x0b\x32\x10.rpc.Transaction\x12\x11\n\tsignature\x18\x02 \x01(\t\"\xb0\x01\n\x05\x42lock\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x1b\n\x13previous_block_hash\x18\x02 \x01(\t\x12,\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x16.rpc.SignedTransaction\x12\x12\n\ndifficulty\x18\x04 \x01(\r\x12\x10\n\x08solution\x18\x05 \x01(\r\x12&\n\x06reward\x18\x06 \x01(\x0b\x32\x16.rpc.SignedTransaction\";\n\x0bSignedBlock\x12\x19\n\x05\x62lock\x18\x01 \x01(\x0b\x32\n.rpc.Block\x12\x11\n\tsignature\x18\x02 \x01(\t\".\n\nBlockChain\x12 \n\x06\x62locks\x18\x01 \x03(\x0b\x32\x10.rpc.SignedBlock\"\x18\n\x16TransactionFeedRequest\"\x12\n\x10\x42lockFeedRequest\"\x1e\n\x0bSyncRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\xb2\x01\n\x03RPC\x12H\n\x0fTransactionFeed\x12\x1b.rpc.TransactionFeedRequest\x1a\x16.rpc.SignedTransaction0\x01\x12\x36\n\tBlockFeed\x12\x15.rpc.BlockFeedRequest\x1a\x10.rpc.SignedBlock0\x01\x12)\n\x04Sync\x12\x10.rpc.SyncRequest\x1a\x0f.rpc.BlockChainb\x06proto3')



_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_SIGNEDTRANSACTION = DESCRIPTOR.message_types_by_name['SignedTransaction']
_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_SIGNEDBLOCK = DESCRIPTOR.message_types_by_name['SignedBlock']
_BLOCKCHAIN = DESCRIPTOR.message_types_by_name['BlockChain']
_TRANSACTIONFEEDREQUEST = DESCRIPTOR.message_types_by_name['TransactionFeedRequest']
_BLOCKFEEDREQUEST = DESCRIPTOR.message_types_by_name['BlockFeedRequest']
_SYNCREQUEST = DESCRIPTOR.message_types_by_name['SyncRequest']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

SignedTransaction = _reflection.GeneratedProtocolMessageType('SignedTransaction', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDTRANSACTION,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SignedTransaction)
  })
_sym_db.RegisterMessage(SignedTransaction)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Block)
  })
_sym_db.RegisterMessage(Block)

SignedBlock = _reflection.GeneratedProtocolMessageType('SignedBlock', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDBLOCK,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SignedBlock)
  })
_sym_db.RegisterMessage(SignedBlock)

BlockChain = _reflection.GeneratedProtocolMessageType('BlockChain', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKCHAIN,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.BlockChain)
  })
_sym_db.RegisterMessage(BlockChain)

TransactionFeedRequest = _reflection.GeneratedProtocolMessageType('TransactionFeedRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONFEEDREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.TransactionFeedRequest)
  })
_sym_db.RegisterMessage(TransactionFeedRequest)

BlockFeedRequest = _reflection.GeneratedProtocolMessageType('BlockFeedRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKFEEDREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.BlockFeedRequest)
  })
_sym_db.RegisterMessage(BlockFeedRequest)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SyncRequest)
  })
_sym_db.RegisterMessage(SyncRequest)

_RPC = DESCRIPTOR.services_by_name['RPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTION._serialized_start=18
  _TRANSACTION._serialized_end=113
  _SIGNEDTRANSACTION._serialized_start=115
  _SIGNEDTRANSACTION._serialized_end=192
  _BLOCK._serialized_start=195
  _BLOCK._serialized_end=371
  _SIGNEDBLOCK._serialized_start=373
  _SIGNEDBLOCK._serialized_end=432
  _BLOCKCHAIN._serialized_start=434
  _BLOCKCHAIN._serialized_end=480
  _TRANSACTIONFEEDREQUEST._serialized_start=482
  _TRANSACTIONFEEDREQUEST._serialized_end=506
  _BLOCKFEEDREQUEST._serialized_start=508
  _BLOCKFEEDREQUEST._serialized_end=526
  _SYNCREQUEST._serialized_start=528
  _SYNCREQUEST._serialized_end=558
  _RPC._serialized_start=561
  _RPC._serialized_end=739
# @@protoc_insertion_point(module_scope)
